spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lucky_draw_dev
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    vn.com.fecredit: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

lucky-draw:
  golden-hour:
    min-duration: 0.25 # 15 minutes for testing
  spin:
    min-cooldown: 5 # 5 seconds for testing
    default-daily-limit: 1000 # Higher limit for testing

security:
  jwt:
    secret: development-secret-key-for-testing-purposes-only
    expiration: 3600000 # 1 hour for testing
